--------------------------------------------------------------------------------
-- hsqldb migration from <= 1.3 to next release
--------------------------------------------------------------------------------
-- Drop constraints 
ALTER TABLE execution DROP CONSTRAINT FK65111AF8FCEAA1D7;
ALTER TABLE reference DROP CONSTRAINT FK6EF34F2BFCEAA1D7;
ALTER TABLE runner_classpaths DROP CONSTRAINT FKDEF546E52522970F;
ALTER TABLE sut_specification DROP CONSTRAINT FK6176AD96FCEAA1D7;
ALTER TABLE system_under_test DROP CONSTRAINT FK60BA29C9FE6FA665;
ALTER TABLE system_under_test DROP CONSTRAINT FK60BA29C92522970F;

-- Changing not nullable columns to nullable
ALTER TABLE EXECUTION ALTER COLUMN SECTIONS SET NULL;
ALTER TABLE EXECUTION ALTER COLUMN RESULTS SET NULL;
ALTER TABLE EXECUTION ALTER COLUMN ERRORID SET NULL;
ALTER TABLE REFERENCE ALTER COLUMN SECTIONS SET NULL;
ALTER TABLE REPOSITORY ALTER COLUMN USERNAME SET NULL;
ALTER TABLE REPOSITORY ALTER COLUMN PASSWORD SET NULL;
ALTER TABLE REPOSITORY_TYPE ALTER COLUMN DOCUMENT_URL_FORMAT SET NULL;
ALTER TABLE REPOSITORY_TYPE ALTER COLUMN TEST_URL_FORMAT SET NULL;
ALTER TABLE REPOSITORY_TYPE ALTER COLUMN REPOSITORY_CLASS SET NULL;
ALTER TABLE RUNNER ALTER COLUMN SERVER_NAME SET NULL;
ALTER TABLE RUNNER ALTER COLUMN SERVER_PORT SET NULL;
ALTER TABLE RUNNER ALTER COLUMN CMD_LINE_TEMPLATE SET NULL;
ALTER TABLE RUNNER ALTER COLUMN MAIN_CLASS SET NULL;

-- Renaming column UID to UIDENT
ALTER TABLE REPOSITORY ALTER COLUMN UID RENAME TO UIDENT;
ALTER TABLE EXECUTION ALTER COLUMN SYSTEM_UNDER_TEST_ID RENAME TO SUT_ID;
ALTER TABLE REFERENCE ALTER COLUMN  SYSTEM_UNDER_TEST_ID RENAME TO SUT_ID;
ALTER TABLE SUT_SPECIFICATION ALTER COLUMN  SYSTEM_UNDER_TEST_ID RENAME TO SUT_ID;
ALTER TABLE SYSTEM_UNDER_TEST_FIXTURECLASSPATHS ALTER COLUMN  SYSTEM_UNDER_TEST_ID RENAME TO SUT_ID;
ALTER TABLE SYSTEM_UNDER_TEST_SUTCLASSPATHS ALTER COLUMN  SYSTEM_UNDER_TEST_ID RENAME TO SUT_ID;

-- Renaming tables SYSTEM_UNDER_TEST* to SUT*
ALTER TABLE SYSTEM_UNDER_TEST RENAME TO SUT;
ALTER TABLE SYSTEM_UNDER_TEST_FIXTURECLASSPATHS RENAME TO SUT_FIXTURE_CLASSPATHS;
ALTER TABLE SYSTEM_UNDER_TEST_SUTCLASSPATHS RENAME TO SUT_CLASSPATHS;

-- Reset empty string to null
UPDATE EXECUTION SET SECTIONS = NULL WHERE SECTIONS = '';
UPDATE EXECUTION SET RESULTS = NULL WHERE RESULTS = '';
UPDATE EXECUTION SET ERRORID = NULL WHERE ERRORID = '';
UPDATE REFERENCE SET SECTIONS = NULL WHERE SECTIONS = '';
UPDATE REPOSITORY SET USERNAME = NULL WHERE USERNAME = '';
UPDATE REPOSITORY SET PASSWORD = NULL WHERE PASSWORD = '';
UPDATE REPOSITORY_TYPE SET DOCUMENT_URL_FORMAT = NULL WHERE DOCUMENT_URL_FORMAT = '';
UPDATE REPOSITORY_TYPE SET TEST_URL_FORMAT = NULL WHERE TEST_URL_FORMAT = '';
UPDATE REPOSITORY_TYPE SET REPOSITORY_CLASS = NULL WHERE REPOSITORY_CLASS = '';
UPDATE RUNNER SET SERVER_NAME = NULL WHERE SERVER_NAME = '';
UPDATE RUNNER SET SERVER_PORT = NULL WHERE SERVER_PORT = '';
UPDATE RUNNER SET CMD_LINE_TEMPLATE = NULL WHERE CMD_LINE_TEMPLATE = '';
UPDATE RUNNER SET MAIN_CLASS = NULL WHERE MAIN_CLASS = '';
UPDATE SUT SET FIXTURE_FACTORY = NULL WHERE FIXTURE_FACTORY = '';
UPDATE SUT SET FIXTURE_FACTORY_ARGS = NULL WHERE FIXTURE_FACTORY_ARGS = '';

