--------------------------------------------------------------------------------
-- PostgreSQL migration from <= 1.3 to next release
--------------------------------------------------------------------------------
-- Drop constraints 
ALTER TABLE EXECUTION DROP CONSTRAINT FK65111AF8FCEAA1D7;
ALTER TABLE REFERENCE DROP CONSTRAINT FK6EF34F2BFCEAA1D7;
ALTER TABLE RUNNER_classpaths DROP CONSTRAINT FKDEF546E52522970F;
ALTER TABLE SUT_SPECIFICATION DROP CONSTRAINT FK6176AD96FCEAA1D7;
ALTER TABLE SYSTEM_UNDER_TEST DROP CONSTRAINT FK60BA29C9FE6FA665;
ALTER TABLE SYSTEM_UNDER_TEST DROP CONSTRAINT FK60BA29C92522970F;
ALTER TABLE SYSTEM_UNDER_TEST_SUT_CLASSPATHS DROP CONSTRAINT fk9ceba672fceaa1d7;
ALTER TABLE SYSTEM_UNDER_TEST_FIXTURE_CLASSPATHS DROP CONSTRAINT fkd04ad469fceaa1d7;

-- Changing not nullable columns to nullable
ALTER TABLE execution ALTER COLUMN sections DROP NOT NULL;
ALTER TABLE execution ALTER COLUMN results DROP NOT NULL;
ALTER TABLE execution ALTER COLUMN errorid DROP NOT NULL;
ALTER TABLE reference ALTER COLUMN sections DROP NOT NULL;
ALTER TABLE repository ALTER COLUMN username DROP NOT NULL;
ALTER TABLE repository ALTER COLUMN password DROP NOT NULL;
ALTER TABLE repository_type ALTER COLUMN document_url_format DROP NOT NULL;
ALTER TABLE repository_type ALTER COLUMN test_url_format DROP NOT NULL;
ALTER TABLE repository_type ALTER COLUMN repository_class DROP NOT NULL;
ALTER TABLE runner ALTER COLUMN server_name DROP NOT NULL;
ALTER TABLE runner ALTER COLUMN server_port DROP NOT NULL;
ALTER TABLE runner ALTER COLUMN cmd_line_template DROP NOT NULL;
ALTER TABLE runner ALTER COLUMN main_class DROP NOT NULL;

-- Renaming columns
ALTER TABLE repository RENAME uid TO uident;
ALTER TABLE execution RENAME system_under_test_id  TO sut_id;
ALTER TABLE reference RENAME system_under_test_id  TO sut_id;
ALTER TABLE sut_specification RENAME system_under_test_id  TO sut_id;
ALTER TABLE system_under_test_fixtureclasspaths RENAME system_under_test_id  TO sut_id;
ALTER TABLE system_under_test_sutclasspaths RENAME system_under_test_id  TO sut_id;

-- Renaming tables SYSTEM_UNDER_TEST* to SUT*
ALTER TABLE system_under_test RENAME TO sut;
ALTER TABLE system_under_test_fixtureclasspaths RENAME TO sut_fixture_classpaths;
ALTER TABLE system_under_test_sutclasspaths RENAME TO sut_classpaths;

-- Reset empty string to null
UPDATE EXECUTION SET SECTIONS = NULL WHERE SECTIONS = '';
UPDATE EXECUTION SET RESULTS = NULL WHERE RESULTS = '';
UPDATE EXECUTION SET ERRORID = NULL WHERE ERRORID = '';
UPDATE REFERENCE SET SECTIONS = NULL WHERE SECTIONS = '';
UPDATE REPOSITORY SET USERNAME = NULL WHERE USERNAME = '';
UPDATE REPOSITORY SET PASSWORD = NULL WHERE PASSWORD = '';
UPDATE REPOSITORY_TYPE SET DOCUMENT_URL_FORMAT = NULL WHERE DOCUMENT_URL_FORMAT = '';
UPDATE REPOSITORY_TYPE SET TEST_URL_FORMAT = NULL WHERE TEST_URL_FORMAT = '';
UPDATE REPOSITORY_TYPE SET REPOSITORY_CLASS = NULL WHERE REPOSITORY_CLASS = '';
UPDATE RUNNER SET SERVER_NAME = NULL WHERE SERVER_NAME = '';
UPDATE RUNNER SET SERVER_PORT = NULL WHERE SERVER_PORT = '';
UPDATE RUNNER SET CMD_LINE_TEMPLATE = NULL WHERE CMD_LINE_TEMPLATE = '';
UPDATE RUNNER SET MAIN_CLASS = NULL WHERE MAIN_CLASS = '';
UPDATE SUT SET FIXTURE_FACTORY = NULL WHERE FIXTURE_FACTORY = '';
UPDATE SUT SET FIXTURE_FACTORY_ARGS = NULL WHERE FIXTURE_FACTORY_ARGS = '';

