--------------------------------------------------------------------------------
-- sqlserver migration from <= 1.3 to next release
--------------------------------------------------------------------------------
-- Drop constraints 
ALTER TABLE EXECUTION DROP CONSTRAINT FK65111AF8FCEAA1D7;
ALTER TABLE REFERENCE DROP CONSTRAINT FK6EF34F2BFCEAA1D7;
ALTER TABLE RUNNER_CLASSPATHS DROP CONSTRAINT FKDEF546E52522970F;
ALTER TABLE SUT_SPECIFICATION DROP CONSTRAINT FK6176AD96FCEAA1D7;
ALTER TABLE SYSTEM_UNDER_TEST DROP CONSTRAINT FK60BA29C9FE6FA665;
ALTER TABLE SYSTEM_UNDER_TEST DROP CONSTRAINT FK60BA29C92522970F;
ALTER TABLE SYSTEM_UNDER_TEST_SUTCLASSPATHS DROP CONSTRAINT FK9CEBA672FCEAA1D7;
ALTER TABLE SYSTEM_UNDER_TEST_FIXTURECLASSPATHS DROP CONSTRAINT FKD04AD469FCEAA1D7;

-- Changing not nullable columns to nullable
ALTER TABLE EXECUTION ALTER COLUMN SECTIONS VARCHAR(50);
ALTER TABLE EXECUTION ALTER COLUMN RESULTS TEXT;
ALTER TABLE EXECUTION ALTER COLUMN ERRORID TEXT;
ALTER TABLE REFERENCE ALTER COLUMN SECTIONS VARCHAR(50);
ALTER TABLE REPOSITORY ALTER COLUMN USERNAME VARCHAR(15);
ALTER TABLE REPOSITORY ALTER COLUMN PASSWORD VARCHAR(15);
ALTER TABLE REPOSITORY_TYPE ALTER COLUMN DOCUMENT_URL_FORMAT VARCHAR(255);
ALTER TABLE REPOSITORY_TYPE ALTER COLUMN TEST_URL_FORMAT VARCHAR(255);
ALTER TABLE REPOSITORY_TYPE ALTER COLUMN REPOSITORY_CLASS VARCHAR(255);
ALTER TABLE RUNNER ALTER COLUMN SERVER_NAME VARCHAR(255);
ALTER TABLE RUNNER ALTER COLUMN SERVER_PORT VARCHAR(8);
ALTER TABLE RUNNER ALTER COLUMN CMD_LINE_TEMPLATE VARCHAR(510);
ALTER TABLE RUNNER ALTER COLUMN MAIN_CLASS VARCHAR(255);

-- Renaming column UID to UIDENT
EXEC SP_RENAME 'REPOSITORY.[UID]', 'UIDENT', 'COLUMN';
EXEC SP_RENAME 'EXECUTION.[SYSTEM_UNDER_TEST_ID]', 'SUT_ID', 'COLUMN';
EXEC SP_RENAME 'REFERENCE.[SYSTEM_UNDER_TEST_ID]', 'SUT_ID', 'COLUMN';
EXEC SP_RENAME 'SUT_SPECIFICATION.[SYSTEM_UNDER_TEST_ID]', 'SUT_ID', 'COLUMN';
EXEC SP_RENAME 'SYSTEM_UNDER_TEST_FIXTURECLASSPATHS.[SYSTEM_UNDER_TEST_ID]', 'SUT_ID', 'COLUMN';
EXEC SP_RENAME 'SYSTEM_UNDER_TEST_SUTCLASSPATHS.[SYSTEM_UNDER_TEST_ID]', 'SUT_ID', 'COLUMN';

-- Renaming tables SYSTEM_UNDER_TEST* to SUT*
EXEC SP_RENAME 'SYSTEM_UNDER_TEST', 'SUT';
EXEC SP_RENAME 'SYSTEM_UNDER_TEST_FIXTURECLASSPATHS', 'SUT_FIXTURE_CLASSPATHS';
EXEC SP_RENAME 'SYSTEM_UNDER_TEST_SUTCLASSPATHS', 'SUT_CLASSPATHS';

-- Reset empty string to null
UPDATE EXECUTION SET SECTIONS = NULL WHERE SECTIONS = '';
UPDATE EXECUTION SET RESULTS = NULL WHERE datalength(RESULTS) = 0;
UPDATE EXECUTION SET ERRORID = NULL WHERE datalength(ERRORID) = 0;
UPDATE REFERENCE SET SECTIONS = NULL WHERE SECTIONS = '';
UPDATE REPOSITORY SET USERNAME = NULL WHERE USERNAME = '';
UPDATE REPOSITORY SET PASSWORD = NULL WHERE PASSWORD = '';
UPDATE REPOSITORY_TYPE SET DOCUMENT_URL_FORMAT = NULL WHERE DOCUMENT_URL_FORMAT = '';
UPDATE REPOSITORY_TYPE SET TEST_URL_FORMAT = NULL WHERE TEST_URL_FORMAT = '';
UPDATE REPOSITORY_TYPE SET REPOSITORY_CLASS = NULL WHERE REPOSITORY_CLASS = '';
UPDATE RUNNER SET SERVER_NAME = NULL WHERE SERVER_NAME = '';
UPDATE RUNNER SET SERVER_PORT = NULL WHERE SERVER_PORT = '';
UPDATE RUNNER SET CMD_LINE_TEMPLATE = NULL WHERE CMD_LINE_TEMPLATE = '';
UPDATE RUNNER SET MAIN_CLASS = NULL WHERE MAIN_CLASS = '';
UPDATE SUT SET FIXTURE_FACTORY = NULL WHERE FIXTURE_FACTORY = '';
UPDATE SUT SET FIXTURE_FACTORY_ARGS = NULL WHERE FIXTURE_FACTORY_ARGS = '';

